/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.CifraDeCesar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alisson
 */
public class Criptografar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Criptografar
     */
    public Criptografar() {
        this.setFrameIcon(new ImageIcon("src\\img\\digitacao.png"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlInforme = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxTexto = new javax.swing.JTextArea();
        jlInforme1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxTextoCriptografado = new javax.swing.JTextArea();
        jbCriptografar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criptografar com Cifra de Cesar");

        jlInforme.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlInforme.setText("Informe um texto no campo abaixo:");

        jtxTexto.setColumns(20);
        jtxTexto.setRows(5);
        jScrollPane1.setViewportView(jtxTexto);

        jlInforme1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlInforme1.setText("Texto Criptografado:");

        jtxTextoCriptografado.setColumns(20);
        jtxTextoCriptografado.setRows(5);
        jScrollPane2.setViewportView(jtxTextoCriptografado);

        jbCriptografar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbCriptografar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        jbCriptografar.setText("Criptografar Texto");
        jbCriptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriptografarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlInforme1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jbCriptografar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCriptografar)
                .addGap(13, 13, 13)
                .addComponent(jlInforme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCriptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriptografarActionPerformed
        if (getJtxTexto().getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo vazio, insira um texto para continuar!", "Alerta", 2);
        } else {
           String textoCriptografado = CifraDeCesar.criptografa(getJtxTexto().getText(), 3);
           getJtxTextoCriptografado().setText(textoCriptografado);
        }
    }//GEN-LAST:event_jbCriptografarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCriptografar;
    private javax.swing.JLabel jlInforme;
    private javax.swing.JLabel jlInforme1;
    private javax.swing.JTextArea jtxTexto;
    private javax.swing.JTextArea jtxTextoCriptografado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the jbCriptografar
     */
    public javax.swing.JButton getJbCriptografar() {
        return jbCriptografar;
    }

    /**
     * @param jbCriptografar the jbCriptografar to set
     */
    public void setJbCriptografar(javax.swing.JButton jbCriptografar) {
        this.jbCriptografar = jbCriptografar;
    }

    /**
     * @return the jlInforme
     */
    public javax.swing.JLabel getJlInforme() {
        return jlInforme;
    }

    /**
     * @param jlInforme the jlInforme to set
     */
    public void setJlInforme(javax.swing.JLabel jlInforme) {
        this.jlInforme = jlInforme;
    }

    /**
     * @return the jlInforme1
     */
    public javax.swing.JLabel getJlInforme1() {
        return jlInforme1;
    }

    /**
     * @param jlInforme1 the jlInforme1 to set
     */
    public void setJlInforme1(javax.swing.JLabel jlInforme1) {
        this.jlInforme1 = jlInforme1;
    }

    /**
     * @return the jtxTexto
     */
    public javax.swing.JTextArea getJtxTexto() {
        return jtxTexto;
    }

    /**
     * @param jtxTexto the jtxTexto to set
     */
    public void setJtxTexto(javax.swing.JTextArea jtxTexto) {
        this.jtxTexto = jtxTexto;
    }

    /**
     * @return the jtxTextoCriptografado
     */
    public javax.swing.JTextArea getJtxTextoCriptografado() {
        return jtxTextoCriptografado;
    }

    /**
     * @param jtxTextoCriptografado the jtxTextoCriptografado to set
     */
    public void setJtxTextoCriptografado(javax.swing.JTextArea jtxTextoCriptografado) {
        this.jtxTextoCriptografado = jtxTextoCriptografado;
    }
}
